%% Container Diagram

flowchart LR
  subgraph Frontend
    NextApp[Next.js app (SSR + client)]
  end
  subgraph Backend
    GoBFF[Go BFF API]
    Worker[Background Worker]
  end
  DB[(Aurora/RDS)]
  Cache[(Redis)]
  Queue[(SQS)]

  NextApp --> GoBFF
  GoBFF --> DB
  GoBFF --> Cache
  GoBFF --> Queue
  Worker --> Queue
  Worker --> DB

  style NextApp fill:#f9f,stroke:#333,stroke-width:1px
  style GoBFF fill:#bbf,stroke:#333,stroke-width:1px
